// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// XAVFSIZLIK: API kalitlari environment variable'lardan olinadi
/// Build: flutter run --dart-define=FIREBASE_WEB_API_KEY=xxx ...
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuXP_98aKQ_Vjr6Zvxo_NjWCAuG-_yaGM',
    appId: '1:541689366619:web:c1fab85bd011362580d77e',
    messagingSenderId: '541689366619',
    projectId: 'topla-app-ef946',
    authDomain: 'topla-app-ef946.firebaseapp.com',
    storageBucket: 'topla-app-ef946.firebasestorage.app',
    measurementId: 'G-LYKWT8CWWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1SzjfYUHr1AkKNXVX6PmigFLAHclHVdQ',
    appId: '1:541689366619:android:41e773be3bffce7380d77e',
    messagingSenderId: '541689366619',
    projectId: 'topla-app-ef946',
    storageBucket: 'topla-app-ef946.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALAkewwmN3N5cGjN16MIgZFCyHLFp4tBE',
    appId: '1:541689366619:ios:1590258b8c7349e980d77e',
    messagingSenderId: '541689366619',
    projectId: 'topla-app-ef946',
    storageBucket: 'topla-app-ef946.firebasestorage.app',
    iosClientId: '541689366619-pbdh4qrpbm0ah87u6tcjht0ri9u0f2l4.apps.googleusercontent.com',
    iosBundleId: 'com.topla.toplaApp',
  );

}