// File generated by FlutterFire CLI.
// Modified for security - API keys from environment variables
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'core/config/env_config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// XAVFSIZLIK: API kalitlari environment variable'lardan olinadi
/// Build: flutter run --dart-define=FIREBASE_WEB_API_KEY=xxx ...
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: EnvConfig.firebaseWebApiKey,
        appId:
            '1:${EnvConfig.firebaseMessagingSenderId}:web:c1fab85bd011362580d77e',
        messagingSenderId: EnvConfig.firebaseMessagingSenderId,
        projectId: EnvConfig.firebaseProjectId,
        authDomain: '${EnvConfig.firebaseProjectId}.firebaseapp.com',
        storageBucket: '${EnvConfig.firebaseProjectId}.firebasestorage.app',
        measurementId: 'G-LYKWT8CWWX',
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: EnvConfig.firebaseAndroidApiKey,
        appId:
            '1:${EnvConfig.firebaseMessagingSenderId}:android:41e773be3bffce7380d77e',
        messagingSenderId: EnvConfig.firebaseMessagingSenderId,
        projectId: EnvConfig.firebaseProjectId,
        storageBucket: '${EnvConfig.firebaseProjectId}.firebasestorage.app',
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: EnvConfig.firebaseIosApiKey,
        appId:
            '1:${EnvConfig.firebaseMessagingSenderId}:ios:1590258b8c7349e980d77e',
        messagingSenderId: EnvConfig.firebaseMessagingSenderId,
        projectId: EnvConfig.firebaseProjectId,
        storageBucket: '${EnvConfig.firebaseProjectId}.firebasestorage.app',
        iosBundleId: 'com.topla.toplaApp',
      );
}
